/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FunctionsV1YoutubeDownloadRouteImport } from './routes/functions.v1.youtube-download'
import { Route as FunctionsV1TwitterDownloadRouteImport } from './routes/functions.v1.twitter-download'
import { Route as FunctionsV1TinyurlToolsRouteImport } from './routes/functions.v1.tinyurl-tools'
import { Route as FunctionsV1TiktokDownloadRouteImport } from './routes/functions.v1.tiktok-download'
import { Route as FunctionsV1SpotifyDownloadRouteImport } from './routes/functions.v1.spotify-download'
import { Route as FunctionsV1SpotifyCollectionInfoRouteImport } from './routes/functions.v1.spotify-collection-info'
import { Route as FunctionsV1PythonProxyRouteImport } from './routes/functions.v1.python-proxy'
import { Route as FunctionsV1LinkedinDownloadRouteImport } from './routes/functions.v1.linkedin-download'
import { Route as FunctionsV1InstagramDownloadRouteImport } from './routes/functions.v1.instagram-download'
import { Route as FunctionsV1FacebookDownloadRouteImport } from './routes/functions.v1.facebook-download'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionsV1YoutubeDownloadRoute =
  FunctionsV1YoutubeDownloadRouteImport.update({
    id: '/functions/v1/youtube-download',
    path: '/functions/v1/youtube-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const FunctionsV1TwitterDownloadRoute =
  FunctionsV1TwitterDownloadRouteImport.update({
    id: '/functions/v1/twitter-download',
    path: '/functions/v1/twitter-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const FunctionsV1TinyurlToolsRoute = FunctionsV1TinyurlToolsRouteImport.update({
  id: '/functions/v1/tinyurl-tools',
  path: '/functions/v1/tinyurl-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionsV1TiktokDownloadRoute =
  FunctionsV1TiktokDownloadRouteImport.update({
    id: '/functions/v1/tiktok-download',
    path: '/functions/v1/tiktok-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const FunctionsV1SpotifyDownloadRoute =
  FunctionsV1SpotifyDownloadRouteImport.update({
    id: '/functions/v1/spotify-download',
    path: '/functions/v1/spotify-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const FunctionsV1SpotifyCollectionInfoRoute =
  FunctionsV1SpotifyCollectionInfoRouteImport.update({
    id: '/functions/v1/spotify-collection-info',
    path: '/functions/v1/spotify-collection-info',
    getParentRoute: () => rootRouteImport,
  } as any)
const FunctionsV1PythonProxyRoute = FunctionsV1PythonProxyRouteImport.update({
  id: '/functions/v1/python-proxy',
  path: '/functions/v1/python-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionsV1LinkedinDownloadRoute =
  FunctionsV1LinkedinDownloadRouteImport.update({
    id: '/functions/v1/linkedin-download',
    path: '/functions/v1/linkedin-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const FunctionsV1InstagramDownloadRoute =
  FunctionsV1InstagramDownloadRouteImport.update({
    id: '/functions/v1/instagram-download',
    path: '/functions/v1/instagram-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const FunctionsV1FacebookDownloadRoute =
  FunctionsV1FacebookDownloadRouteImport.update({
    id: '/functions/v1/facebook-download',
    path: '/functions/v1/facebook-download',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/functions/v1/facebook-download': typeof FunctionsV1FacebookDownloadRoute
  '/functions/v1/instagram-download': typeof FunctionsV1InstagramDownloadRoute
  '/functions/v1/linkedin-download': typeof FunctionsV1LinkedinDownloadRoute
  '/functions/v1/python-proxy': typeof FunctionsV1PythonProxyRoute
  '/functions/v1/spotify-collection-info': typeof FunctionsV1SpotifyCollectionInfoRoute
  '/functions/v1/spotify-download': typeof FunctionsV1SpotifyDownloadRoute
  '/functions/v1/tiktok-download': typeof FunctionsV1TiktokDownloadRoute
  '/functions/v1/tinyurl-tools': typeof FunctionsV1TinyurlToolsRoute
  '/functions/v1/twitter-download': typeof FunctionsV1TwitterDownloadRoute
  '/functions/v1/youtube-download': typeof FunctionsV1YoutubeDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/functions/v1/facebook-download': typeof FunctionsV1FacebookDownloadRoute
  '/functions/v1/instagram-download': typeof FunctionsV1InstagramDownloadRoute
  '/functions/v1/linkedin-download': typeof FunctionsV1LinkedinDownloadRoute
  '/functions/v1/python-proxy': typeof FunctionsV1PythonProxyRoute
  '/functions/v1/spotify-collection-info': typeof FunctionsV1SpotifyCollectionInfoRoute
  '/functions/v1/spotify-download': typeof FunctionsV1SpotifyDownloadRoute
  '/functions/v1/tiktok-download': typeof FunctionsV1TiktokDownloadRoute
  '/functions/v1/tinyurl-tools': typeof FunctionsV1TinyurlToolsRoute
  '/functions/v1/twitter-download': typeof FunctionsV1TwitterDownloadRoute
  '/functions/v1/youtube-download': typeof FunctionsV1YoutubeDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/functions/v1/facebook-download': typeof FunctionsV1FacebookDownloadRoute
  '/functions/v1/instagram-download': typeof FunctionsV1InstagramDownloadRoute
  '/functions/v1/linkedin-download': typeof FunctionsV1LinkedinDownloadRoute
  '/functions/v1/python-proxy': typeof FunctionsV1PythonProxyRoute
  '/functions/v1/spotify-collection-info': typeof FunctionsV1SpotifyCollectionInfoRoute
  '/functions/v1/spotify-download': typeof FunctionsV1SpotifyDownloadRoute
  '/functions/v1/tiktok-download': typeof FunctionsV1TiktokDownloadRoute
  '/functions/v1/tinyurl-tools': typeof FunctionsV1TinyurlToolsRoute
  '/functions/v1/twitter-download': typeof FunctionsV1TwitterDownloadRoute
  '/functions/v1/youtube-download': typeof FunctionsV1YoutubeDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/sitemap.xml'
    | '/functions/v1/facebook-download'
    | '/functions/v1/instagram-download'
    | '/functions/v1/linkedin-download'
    | '/functions/v1/python-proxy'
    | '/functions/v1/spotify-collection-info'
    | '/functions/v1/spotify-download'
    | '/functions/v1/tiktok-download'
    | '/functions/v1/tinyurl-tools'
    | '/functions/v1/twitter-download'
    | '/functions/v1/youtube-download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/sitemap.xml'
    | '/functions/v1/facebook-download'
    | '/functions/v1/instagram-download'
    | '/functions/v1/linkedin-download'
    | '/functions/v1/python-proxy'
    | '/functions/v1/spotify-collection-info'
    | '/functions/v1/spotify-download'
    | '/functions/v1/tiktok-download'
    | '/functions/v1/tinyurl-tools'
    | '/functions/v1/twitter-download'
    | '/functions/v1/youtube-download'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/sitemap.xml'
    | '/functions/v1/facebook-download'
    | '/functions/v1/instagram-download'
    | '/functions/v1/linkedin-download'
    | '/functions/v1/python-proxy'
    | '/functions/v1/spotify-collection-info'
    | '/functions/v1/spotify-download'
    | '/functions/v1/tiktok-download'
    | '/functions/v1/tinyurl-tools'
    | '/functions/v1/twitter-download'
    | '/functions/v1/youtube-download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FunctionsV1FacebookDownloadRoute: typeof FunctionsV1FacebookDownloadRoute
  FunctionsV1InstagramDownloadRoute: typeof FunctionsV1InstagramDownloadRoute
  FunctionsV1LinkedinDownloadRoute: typeof FunctionsV1LinkedinDownloadRoute
  FunctionsV1PythonProxyRoute: typeof FunctionsV1PythonProxyRoute
  FunctionsV1SpotifyCollectionInfoRoute: typeof FunctionsV1SpotifyCollectionInfoRoute
  FunctionsV1SpotifyDownloadRoute: typeof FunctionsV1SpotifyDownloadRoute
  FunctionsV1TiktokDownloadRoute: typeof FunctionsV1TiktokDownloadRoute
  FunctionsV1TinyurlToolsRoute: typeof FunctionsV1TinyurlToolsRoute
  FunctionsV1TwitterDownloadRoute: typeof FunctionsV1TwitterDownloadRoute
  FunctionsV1YoutubeDownloadRoute: typeof FunctionsV1YoutubeDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/v1/youtube-download': {
      id: '/functions/v1/youtube-download'
      path: '/functions/v1/youtube-download'
      fullPath: '/functions/v1/youtube-download'
      preLoaderRoute: typeof FunctionsV1YoutubeDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/v1/twitter-download': {
      id: '/functions/v1/twitter-download'
      path: '/functions/v1/twitter-download'
      fullPath: '/functions/v1/twitter-download'
      preLoaderRoute: typeof FunctionsV1TwitterDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/v1/tinyurl-tools': {
      id: '/functions/v1/tinyurl-tools'
      path: '/functions/v1/tinyurl-tools'
      fullPath: '/functions/v1/tinyurl-tools'
      preLoaderRoute: typeof FunctionsV1TinyurlToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/v1/tiktok-download': {
      id: '/functions/v1/tiktok-download'
      path: '/functions/v1/tiktok-download'
      fullPath: '/functions/v1/tiktok-download'
      preLoaderRoute: typeof FunctionsV1TiktokDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/v1/spotify-download': {
      id: '/functions/v1/spotify-download'
      path: '/functions/v1/spotify-download'
      fullPath: '/functions/v1/spotify-download'
      preLoaderRoute: typeof FunctionsV1SpotifyDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/v1/spotify-collection-info': {
      id: '/functions/v1/spotify-collection-info'
      path: '/functions/v1/spotify-collection-info'
      fullPath: '/functions/v1/spotify-collection-info'
      preLoaderRoute: typeof FunctionsV1SpotifyCollectionInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/v1/python-proxy': {
      id: '/functions/v1/python-proxy'
      path: '/functions/v1/python-proxy'
      fullPath: '/functions/v1/python-proxy'
      preLoaderRoute: typeof FunctionsV1PythonProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/v1/linkedin-download': {
      id: '/functions/v1/linkedin-download'
      path: '/functions/v1/linkedin-download'
      fullPath: '/functions/v1/linkedin-download'
      preLoaderRoute: typeof FunctionsV1LinkedinDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/v1/instagram-download': {
      id: '/functions/v1/instagram-download'
      path: '/functions/v1/instagram-download'
      fullPath: '/functions/v1/instagram-download'
      preLoaderRoute: typeof FunctionsV1InstagramDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/v1/facebook-download': {
      id: '/functions/v1/facebook-download'
      path: '/functions/v1/facebook-download'
      fullPath: '/functions/v1/facebook-download'
      preLoaderRoute: typeof FunctionsV1FacebookDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FunctionsV1FacebookDownloadRoute: FunctionsV1FacebookDownloadRoute,
  FunctionsV1InstagramDownloadRoute: FunctionsV1InstagramDownloadRoute,
  FunctionsV1LinkedinDownloadRoute: FunctionsV1LinkedinDownloadRoute,
  FunctionsV1PythonProxyRoute: FunctionsV1PythonProxyRoute,
  FunctionsV1SpotifyCollectionInfoRoute: FunctionsV1SpotifyCollectionInfoRoute,
  FunctionsV1SpotifyDownloadRoute: FunctionsV1SpotifyDownloadRoute,
  FunctionsV1TiktokDownloadRoute: FunctionsV1TiktokDownloadRoute,
  FunctionsV1TinyurlToolsRoute: FunctionsV1TinyurlToolsRoute,
  FunctionsV1TwitterDownloadRoute: FunctionsV1TwitterDownloadRoute,
  FunctionsV1YoutubeDownloadRoute: FunctionsV1YoutubeDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
