// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use fallback empty strings so that createClient() does NOT throw at module load
// time when env vars are absent (e.g. Cloudflare Workers production build).
// Any actual Supabase operation will fail gracefully at call-time instead of
// crashing the entire React app on startup.
const SUPABASE_URL = String(import.meta.env.VITE_SUPABASE_URL ?? "");
const SUPABASE_PUBLISHABLE_KEY = String(import.meta.env.VITE_SUPABASE_ANON_KEY ?? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Guard localStorage access — it is not available during SSR on Cloudflare Workers.
const isBrowser = typeof window !== "undefined" && typeof localStorage !== "undefined";

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://placeholder.supabase.co",
  SUPABASE_PUBLISHABLE_KEY || "placeholder",
  {
    auth: {
      ...(isBrowser ? { storage: localStorage } : {}),
      persistSession: isBrowser,
      autoRefreshToken: isBrowser,
    },
  }
);